apiVersion: v1
kind: Service
metadata:
  name: mariadb-qna-service
  namespace: mariadb-namespace
spec:
  selector:
    app: mariadb-qna
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
