apiVersion: v1
kind: Namespace
metadata:
  name: maria-name

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-initdb-config
  namespace: maria-name
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS userDB;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-mariadb-deployment
  namespace: maria-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-mariadb
  template:
    metadata:
      labels:
        app: user-service-mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: mariadb-initdb-config  # ConfigMap을 마운트하는 부분 추가
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: user-service-mariadb-pvc
        - name: mariadb-initdb-config  # ConfigMap을 volumes에 추가
          configMap:
            name: mariadb-initdb-config

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-mariadb-service
  namespace: maria-name
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: user-service-mariadb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-mariadb-pvc
  namespace: maria-name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi