server:
  port: 9000 # 서비스 포트 번호

spring:
  application:
    name: auth-service

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans