apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-full-access-binding
subjects:
  - kind: ServiceAccount
    name: traefik-account  # Traefik의 서비스 계정 이름
    namespace: default     # Traefik이 위치한 네임스페이스
roleRef:
  kind: ClusterRole
  name: traefik-full-access  # 앞에서 만든 ClusterRole 이름
  apiGroup: rbac.authorization.k8s.io
