apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-gateway
#  namespace: msa-namespace
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 9000
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  name: user-port
          - path: /QnA
            pathType: Prefix
            backend:
              service:
                name: qna-service
                port:
                  number: 8120
          - path: /att
            pathType: Prefix
            backend:
              service:
                name: attendance-service
                port:
                  number: 8200
          - path: /lecture
            pathType: Prefix
            backend:
              service:
                name: lecture-service
                port:
                  number: 8300
          - path: /vacation
            pathType: Prefix
            backend:
              service:
                name: vacation-service
                port:
                  number: 8300