apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msa-gateway
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  name: auth-port
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  name: user-port