apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-service-deployment
  namespace: msa-namespace  # 네임스페이스 지정
spec:
  replicas: 3  # 파드 수
  selector:
    matchLabels:
      app: qna-service
  template:
    metadata:
      labels:
        app: qna-service
    spec:
      containers:
        - name: qna-service-container
          image: suidori/qna-service:msa.k8.01 # 서비스가 사용할 도커 이미지
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb-qna-service.mariadb-namespace.svc.cluster.local:3306/qna?serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USER_NAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: mysecretkey
            - name: USER_SERVICE
              value: "http://user-service.msa-namespace.svc.cluster.local:8100"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: msa-k8s-configmap
                  key: management-zipkin-tracing-endpoint
          ports:
            - containerPort: 8100  # 애플리케이션 포트 (서비스가 리슨하는 포트)
