apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-service-deployment
  namespace: msa-namespace  # 네임스페이스 지정
spec:
  replicas: 3  # 파드 수
  selector:
    matchLabels:
      app: qna-service
  template:
    metadata:
      labels:
        app: qna-service
    spec:
      containers:
        - name: qna-service-container
          image: leetorrl/qna-service:msa.k8.10 # 서비스가 사용할 도커 이미지
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb-service.mariadb-namespace.svc.cluster.local:3306/education?serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-password
            - name: USER_SERVICE
              value: "http://user-service.msa-namespace.svc.cluster.local:8100"
          ports:
            - containerPort: 8100  # 애플리케이션 포트 (서비스가 리슨하는 포트)
