apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: msa-namespace  # 네임스페이스 지정
spec:
  selector:
    app: user-service  # Deployment와 연결될 레이블
  ports:
    - protocol: TCP
      port: 8100  # 클러스터 내 포트
      targetPort: 8100  # 컨테이너 내 포트
  type: LoadBalancer  # 외부 접근을 위한 LoadBalancer 타입
