server:
  port: 8761  # Eureka ?? ??

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false  # ??? ?? ??? ???? ??
    fetch-registry: false        # ????? ?? ?? ???
  server:
    enable-self-preservation: false # ?? ?? ?? ???? (???)
