apiVersion: v1
kind: ConfigMap
metadata:
  name: public-key
#  namespace: msa-namespace  # 네임스페이스 지정 (배포하려는 네임스페이스)
data:
  public.key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkTn4d3iP0WvBAgcYz3Rs
    WJ7UlMeG+IiagpE9HP1XU5Cup3xfzAJQ0EZcAQZEZ82JH8QzEdcoKccvtVivKS4X
    shUY+R4n+Ym96PnJCqacMXQzxo0vwT8oLQtOofwFM+dncwpUq+9QVwf22MHtcXan
    OUetKGLxYHK5GN9kMRuyIMqpsvEorOM4WxcYgQizFHR4U4Ib8sujX63wdGm70tSK
    VXXVS5kZafveJirIqe+pGwMbWAnBvGQp9CC2/YloQhuFFRvSrPhlFuTjI2hFUkEj
    tAGhfSqWtxTzQyujg2CNTTcX+BBaIvUJARFwU3FTnrJBlKP6NgfA0gYNmDpkN5Aa
    swIDAQAB
    -----END PUBLIC KEY-----
