apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
        - name: attendance-service
          image: nginx:alpine
          ports:
            - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  selector:
    app: attendance-service
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP
