apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture-service
  template:
    metadata:
      labels:
        app: lecture-service
    spec:
      containers:
        - name: lecture-service
          image: nginx:alpine  # 기본 Nginx 이미지를 사용
          ports:
            - containerPort: 8300

---
apiVersion: v1
kind: Service
metadata:
  name: lecture-service
spec:
  selector:
    app: lecture-service
  ports:
    - protocol: TCP
      port: 8300
      targetPort: 8300
  type: ClusterIP
