apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vacation-service
  template:
    metadata:
      labels:
        app: vacation-service
    spec:
      containers:
        - name: vacation-service
          image: nginx:alpine  # 기본 Nginx 이미지를 사용
          ports:
            - containerPort: 8400

---
apiVersion: v1
kind: Service
metadata:
  name: vacation-service
spec:
  selector:
    app: vacation-service
  ports:
    - protocol: TCP
      port: 8400
      targetPort: 8400
  type: ClusterIP
