apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: msa-namespace  # 네임스페이스 지정
spec:
  replicas: 3  # 파드 수
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          image: suidori/auth-service:msa.k8.01 # 서비스가 사용할 도커 이미지
          ports:
            - containerPort: 9000  # 애플리케이션 포트 (서비스가 리슨하는 포트)
